### ISSUE TITLE
Take categories in ENV too

### ISSUE THREAD

**Issue by mchangrh** [erdnaxeli/castblock#16]
Currently, castblock won't run properly in docker-compose since arguments can't be passed into a non-build context.

Crystal can get the environment variables from the process
https://crystal-lang.org/api/1.0.0/ENV.html

the variable might have to be set like
```
CATEGORIES=["sponsor", "selfpromo"]
```

Sample docker-compose
```yml
version: '3.3'
services:
    castblock:
        network_mode: host
        image: erdnaxeli/castblock
        environment:
        - CATEGORIES=["sponsor", "selfpromo"]
```
